/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacion;

import control.Actividad;
import control.Socio;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import persistencia.PActividad;
import persistencia.PBarco;

/**
 *
 * @author Jhon
 */
public class FActividad extends javax.swing.JFrame {

    private Actividad a;
    private PActividad actividadBD;

    public FActividad() {
        initComponents();
        actividadBD = new PActividad();
        cargarLista();
        visibilidad(false);
    }

    public PActividad getActividadBD() {
        return actividadBD;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Lateral = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        crear = new javax.swing.JPanel();
        textoCrear = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visualizar = new javax.swing.JPanel();
        textoVisualizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actualizar = new javax.swing.JPanel();
        textoActualizar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eliminar = new javax.swing.JPanel();
        textoEliminar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        limpiar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoCapitan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textoCambia = new javax.swing.JLabel();
        cajaDestino = new javax.swing.JTextField();
        comboIdentificacionSalidas = new javax.swing.JComboBox<>();
        textoIdentificacionEditar = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        cajaFecha = new javax.swing.JFormattedTextField();
        cajaHora = new javax.swing.JFormattedTextField();
        comboBarcos = new javax.swing.JComboBox<>();
        comboCapitanes = new javax.swing.JComboBox<>();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Sail_96px.png")).getImage());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1270, 720));
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(224, 228, 205));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lateral.setBackground(new java.awt.Color(105, 212, 232));

        Menu.setBackground(new java.awt.Color(105, 212, 232));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menu");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Menu_64px.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(19, 19, 19))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        crear.setBackground(new java.awt.Color(85, 192, 212));
        crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearMouseClicked(evt);
            }
        });

        textoCrear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoCrear.setForeground(new java.awt.Color(255, 255, 255));
        textoCrear.setText("Crear");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_User_Male_32px.png"))); // NOI18N

        javax.swing.GroupLayout crearLayout = new javax.swing.GroupLayout(crear);
        crear.setLayout(crearLayout);
        crearLayout.setHorizontalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(textoCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearLayout.setVerticalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textoCrear))
                .addGap(28, 28, 28))
        );

        visualizar.setBackground(new java.awt.Color(125, 232, 252));
        visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizarMouseClicked(evt);
            }
        });

        textoVisualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        textoVisualizar.setText("Visualizar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_List_View_32px.png"))); // NOI18N

        javax.swing.GroupLayout visualizarLayout = new javax.swing.GroupLayout(visualizar);
        visualizar.setLayout(visualizarLayout);
        visualizarLayout.setHorizontalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addComponent(textoVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        visualizarLayout.setVerticalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textoVisualizar))
                .addGap(28, 28, 28))
        );

        actualizar.setBackground(new java.awt.Color(85, 192, 212));
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarMouseClicked(evt);
            }
        });

        textoActualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoActualizar.setForeground(new java.awt.Color(255, 255, 255));
        textoActualizar.setText("Actualizar");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Update_User_32px.png"))); // NOI18N

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addGap(57, 57, 57)
                .addComponent(textoActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(textoActualizar))
                .addGap(28, 28, 28))
        );

        eliminar.setBackground(new java.awt.Color(125, 232, 252));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        textoEliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        textoEliminar.setText("Eliminar");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Denied_32px.png"))); // NOI18N

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar);
        eliminar.setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addGap(57, 57, 57)
                .addComponent(textoEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(textoEliminar))
                .addGap(28, 28, 28))
        );

        limpiar.setBackground(new java.awt.Color(85, 192, 212));
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Limpiar");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Clear_Symbol_32px.png"))); // NOI18N

        javax.swing.GroupLayout limpiarLayout = new javax.swing.GroupLayout(limpiar);
        limpiar.setLayout(limpiarLayout);
        limpiarLayout.setHorizontalGroup(
            limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(limpiarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel14)
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        limpiarLayout.setVerticalGroup(
            limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, limpiarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout LateralLayout = new javax.swing.GroupLayout(Lateral);
        Lateral.setLayout(LateralLayout);
        LateralLayout.setHorizontalGroup(
            LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(visualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LateralLayout.setVerticalGroup(
            LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Fondo.add(Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        jPanel1.setBackground(new java.awt.Color(167, 219, 217));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Salidas del barco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 319, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(35, 35, 35))
        );

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1270, 130));

        jPanel2.setBackground(new java.awt.Color(224, 228, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoCapitan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCapitan.setText("Capitan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Número matricula");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Fecha");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Hora");

        textoCambia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCambia.setText("Destino");

        cajaDestino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cajaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaDestinoKeyTyped(evt);
            }
        });

        comboIdentificacionSalidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textoIdentificacionEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoIdentificacionEditar.setText("Id de salida");

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Save_32px.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        try {
            cajaFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cajaFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            cajaHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cajaHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        comboBarcos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        comboCapitanes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCambia)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(textoCapitan)
                    .addComponent(textoIdentificacionEditar)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(comboIdentificacionSalidas, 0, 395, Short.MAX_VALUE)
                    .addComponent(cajaFecha)
                    .addComponent(cajaHora)
                    .addComponent(comboBarcos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCapitanes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdentificacionEditar)
                    .addComponent(comboIdentificacionSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCapitan)
                            .addComponent(comboCapitanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cajaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCambia)
                            .addComponent(cajaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 890, 470));

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(102, 102, 102));
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        Fondo.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        if (actividadBD != null) {
            actividadBD.cerrarConexion(); //Cierro conexión de la base de datos actividad
        }
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseClicked
        if (comboCapitanes.getSelectedIndex() != -1 && comboBarcos.getSelectedIndex() != -1 
                && !cajaFecha.getText().isEmpty() && !cajaHora.getText().isEmpty() 
                && !cajaDestino.getText().isEmpty()) { //Verifico que tenga infomación los textfield
            a = new Actividad(comboCapitanes.getSelectedItem().toString(), 
                    Integer.parseInt(comboBarcos.getSelectedItem().toString()), 
                    cajaFecha.getText(), cajaHora.getText(), cajaDestino.getText(), false); //Cargo el objeto de actividad con la información de los campos
            actividadBD.crearActividad(a);
            limpiarCajas();
        } else {
            JOptionPane.showMessageDialog(null, "Falto uno de los datos", "Error en operación", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_crearMouseClicked

    private void visualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarMouseClicked
        FListas fl = new FListas();
        setVisible(false);
        fl.setInterfazActividad(this);
        fl.insertarModeloTabla("actividad");
        fl.setVisible(true);
        
    }//GEN-LAST:event_visualizarMouseClicked

    private void actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseClicked
        cargarActividades();
        visibilidad(true);
        limpiarCajas();
        cargarLista();
        textoEliminar.setText("Regresar");
    }//GEN-LAST:event_actualizarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        if (textoEliminar.getText().equals("Regresar")) {
            visibilidad(false);
            textoEliminar.setText("Eliminar");
        } else {
            textoActualizar.setText("Eliminar");
            textoEliminar.setText("Regresar");
            visibilidad(true);
            textoEliminar.setVisible(true);
            botonGuardar.setText("Borrar");
            cargarLista(); 
            cargarActividades();
        }
    }//GEN-LAST:event_eliminarMouseClicked

    private void limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMouseClicked
        limpiarCajas();
    }//GEN-LAST:event_limpiarMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        if (actividadBD != null) {
            actividadBD.cerrarConexion(); //Cierro conexión de la base de datos actividad
        }
        setVisible(false);
        new FMenu().setVisible(true);
    }//GEN-LAST:event_MenuMouseClicked

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if (comboIdentificacionSalidas.getSelectedIndex() != -1) {
            comboIdentificacionSalidas.setEnabled(false);
            if (botonGuardar.getText().equals("Borrar")) {
                activar(false); 
            }
            a = actividadBD.buscarSalida(comboIdentificacionSalidas.getSelectedItem().toString());
            comboCapitanes.setSelectedItem(a.getIdentificacionNavegante());
            comboBarcos.setSelectedItem(String.valueOf(a.getNumeroMatricula()));
            cajaFecha.setText(a.getFecha());
            cajaHora.setText(a.getHora());
            cajaDestino.setText(a.getDestino());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (comboIdentificacionSalidas.getSelectedIndex() != -1) {
            if (botonGuardar.getText().equals("Borrar")) { //Borra o si no actualiza
                actividadBD.eliminar(comboIdentificacionSalidas.getSelectedItem().toString()); //elimina una actividad de la base de datos
            } else {
                if (comboIdentificacionSalidas.getSelectedIndex() != -1 && comboCapitanes.getSelectedIndex() != -1 && comboBarcos.getSelectedIndex() != -1 && !cajaFecha.getText().isEmpty() && !cajaHora.getText().isEmpty() && !cajaDestino.getText().isEmpty()) {
                    a = new Actividad(Integer.parseInt(comboIdentificacionSalidas.getSelectedItem().toString()), 
                            comboCapitanes.getSelectedItem().toString(), 
                            Integer.parseInt(comboBarcos.getSelectedItem().toString()), 
                            cajaFecha.getText(), cajaHora.getText(), 
                            cajaDestino.getText(), false);
                    actividadBD.actualizarActividad(a); //Actualizar con un objeto de actividad
                }
            }
        }
        textoEliminar.setText("Eliminar");
        activar(true);
        visibilidad(false);
        limpiarCajas();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void cajaDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDestinoKeyTyped
        limitarLetrasCajas(20, cajaDestino, evt);
    }//GEN-LAST:event_cajaDestinoKeyTyped
    
    //Metodos propios
    
    //Elimina todo lo escrito en los campos de la interfaz    
    private void limpiarCajas () {
        cajaDestino.setText("");
        comboCapitanes.setSelectedIndex(-1);
        comboBarcos.setSelectedIndex(-1);
        cajaFecha.setText("");
        cajaHora.setText("");
    }
    
    //Activa o desactiva las cajas cuando se elimina
    private void activar (boolean estado) {
        cajaDestino.setEnabled(estado);
        comboBarcos.setEnabled(estado);
        comboCapitanes.setEnabled(estado);
        cajaFecha.setEnabled(estado);
        cajaHora.setEnabled(estado);
        textoActualizar.setVisible(estado);
    }
    
    //Cambia la visibilidad de algunas cajas
    private void visibilidad (boolean estado) {
        comboIdentificacionSalidas.setVisible(estado);
        textoIdentificacionEditar.setVisible(estado);
        botonBuscar.setVisible(estado);
        botonGuardar.setVisible(estado);
        comboIdentificacionSalidas.setEnabled(estado);
        estado = !estado;
        crear.setEnabled(estado);
        visualizar.setEnabled(estado);
        eliminar.setEnabled(estado);
        textoCrear.setVisible(estado);
        textoVisualizar.setVisible(estado);
        jLabel1.setVisible(estado);
        jLabel3.setVisible(estado);
        jLabel10.setVisible(estado);
    }
    
    //Metodo para limitar la cantidad de texto que se le ingresa
    private void limitarLetrasCajas (int limite, javax.swing.JTextField caja, java.awt.event.KeyEvent e) {
        if (caja.getText().length() >= limite) {
            getToolkit().beep();
            e.consume();
        }
    }
    
    //Carga las listas
    private void cargarLista () {
        comboCapitanes.removeAllItems();
        LinkedList lista = actividadBD.Navegantes();
        for (int i = 0; i < lista.size(); i++) {
            comboCapitanes.addItem(lista.get(i).toString());
        }
        comboCapitanes.setSelectedIndex(-1);
        comboBarcos.removeAllItems();
        PBarco barcoBD = new PBarco();
        lista = barcoBD.listaBarcos();
        for (int i = 0; i < lista.size(); i++) {
            comboBarcos.addItem(lista.get(i).toString());
        }
        comboBarcos.setSelectedIndex(-1);
        barcoBD.cerrarConexion();
    }
    
    //Carga las actividades
    private void cargarActividades () {
        comboIdentificacionSalidas.removeAllItems();
        LinkedList lista = actividadBD.Actividades();
        for (int i = 0; i < lista.size(); i++) {
            comboIdentificacionSalidas.addItem(lista.get(i).toString());
        }
        comboIdentificacionSalidas.setSelectedIndex(-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Lateral;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel actualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField cajaDestino;
    private javax.swing.JFormattedTextField cajaFecha;
    private javax.swing.JFormattedTextField cajaHora;
    private javax.swing.JLabel cerrar;
    private javax.swing.JComboBox<String> comboBarcos;
    private javax.swing.JComboBox<String> comboCapitanes;
    private javax.swing.JComboBox<String> comboIdentificacionSalidas;
    private javax.swing.JPanel crear;
    private javax.swing.JPanel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel limpiar;
    private javax.swing.JLabel textoActualizar;
    private javax.swing.JLabel textoCambia;
    private javax.swing.JLabel textoCapitan;
    private javax.swing.JLabel textoCrear;
    private javax.swing.JLabel textoEliminar;
    private javax.swing.JLabel textoIdentificacionEditar;
    private javax.swing.JLabel textoVisualizar;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel visualizar;
    // End of variables declaration//GEN-END:variables
}
