/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacion;

import control.Barco;
import control.Socio;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import persistencia.PBarco;
import persistencia.PSocio;

/**
 *
 * @author Jhon
 */
public class FBarco extends javax.swing.JFrame {

    private Barco b;
    private PBarco barcoBD;
    
    public FBarco() {
        initComponents();
        barcoBD = new PBarco();
        cargarListas();
        visibilidad(false);
    }

    public PBarco getBarcoBD() {
        return barcoBD;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Lateral = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        crear = new javax.swing.JPanel();
        textoCrear = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visualizar = new javax.swing.JPanel();
        textoVisualizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actualizar = new javax.swing.JPanel();
        textoActualizar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eliminar = new javax.swing.JPanel();
        textoEliminar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        limpiar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoIdentificacionCrear = new javax.swing.JLabel();
        textoPropietario = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cajaMatricula = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        comboMatricula = new javax.swing.JComboBox<>();
        textoIdentificacionEditar = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        comboPropietario = new javax.swing.JComboBox<>();
        comboAmarre = new javax.swing.JComboBox<>();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Sail_96px.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(224, 228, 205));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lateral.setBackground(new java.awt.Color(105, 212, 232));

        Menu.setBackground(new java.awt.Color(105, 212, 232));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menu");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Menu_64px.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(19, 19, 19))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        crear.setBackground(new java.awt.Color(85, 192, 212));
        crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearMouseClicked(evt);
            }
        });

        textoCrear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoCrear.setForeground(new java.awt.Color(255, 255, 255));
        textoCrear.setText("Crear");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_User_Male_32px.png"))); // NOI18N

        javax.swing.GroupLayout crearLayout = new javax.swing.GroupLayout(crear);
        crear.setLayout(crearLayout);
        crearLayout.setHorizontalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(textoCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearLayout.setVerticalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textoCrear))
                .addGap(28, 28, 28))
        );

        visualizar.setBackground(new java.awt.Color(125, 232, 252));
        visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizarMouseClicked(evt);
            }
        });

        textoVisualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        textoVisualizar.setText("Visualizar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_List_View_32px.png"))); // NOI18N

        javax.swing.GroupLayout visualizarLayout = new javax.swing.GroupLayout(visualizar);
        visualizar.setLayout(visualizarLayout);
        visualizarLayout.setHorizontalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addComponent(textoVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        visualizarLayout.setVerticalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textoVisualizar))
                .addGap(28, 28, 28))
        );

        actualizar.setBackground(new java.awt.Color(85, 192, 212));
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarMouseClicked(evt);
            }
        });

        textoActualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoActualizar.setForeground(new java.awt.Color(255, 255, 255));
        textoActualizar.setText("Actualizar");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Update_User_32px.png"))); // NOI18N

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addGap(57, 57, 57)
                .addComponent(textoActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(textoActualizar))
                .addGap(28, 28, 28))
        );

        eliminar.setBackground(new java.awt.Color(125, 232, 252));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        textoEliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        textoEliminar.setText("Eliminar");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Denied_32px.png"))); // NOI18N

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar);
        eliminar.setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addGap(57, 57, 57)
                .addComponent(textoEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(textoEliminar))
                .addGap(28, 28, 28))
        );

        limpiar.setBackground(new java.awt.Color(85, 192, 212));
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Limpiar");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Clear_Symbol_32px.png"))); // NOI18N

        javax.swing.GroupLayout limpiarLayout = new javax.swing.GroupLayout(limpiar);
        limpiar.setLayout(limpiarLayout);
        limpiarLayout.setHorizontalGroup(
            limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(limpiarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel14)
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        limpiarLayout.setVerticalGroup(
            limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, limpiarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout LateralLayout = new javax.swing.GroupLayout(Lateral);
        Lateral.setLayout(LateralLayout);
        LateralLayout.setHorizontalGroup(
            LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(visualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LateralLayout.setVerticalGroup(
            LateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Fondo.add(Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        jPanel1.setBackground(new java.awt.Color(167, 219, 217));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Barco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 319, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(35, 35, 35))
        );

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1270, 130));

        jPanel2.setBackground(new java.awt.Color(224, 228, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoIdentificacionCrear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoIdentificacionCrear.setText("Número matricula");

        textoPropietario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoPropietario.setText("Propietario");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Numero amarre");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Nombre");

        cajaMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cajaMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaMatriculaKeyTyped(evt);
            }
        });

        cajaNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cajaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreKeyTyped(evt);
            }
        });

        comboMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textoIdentificacionEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoIdentificacionEditar.setText("Número matricula");

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Save_32px.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        comboPropietario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        comboAmarre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(textoIdentificacionCrear)
                    .addComponent(textoIdentificacionEditar)
                    .addComponent(textoPropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(comboMatricula, 0, 395, Short.MAX_VALUE)
                    .addComponent(cajaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(comboPropietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAmarre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoIdentificacionEditar)
                            .addComponent(botonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoIdentificacionCrear)
                            .addComponent(cajaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comboAmarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoPropietario)
                            .addComponent(comboPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 890, 470));

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cerrar.setForeground(new java.awt.Color(102, 102, 102));
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        Fondo.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        if (barcoBD != null) {
            barcoBD.cerrarConexion();
        }
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseClicked
        if (!cajaMatricula.getText().isEmpty() && comboPropietario.getSelectedIndex() != -1 && comboAmarre.getSelectedIndex() != -1 && !cajaNombre.getText().isEmpty()) {
            cargarInterfazABarco();
            barcoBD.crearBarco(b);
            limpiarCajas();
        } else {
            JOptionPane.showMessageDialog(null, "Falto uno de los datos número de matricula, número de amarre, propietario o nombre del barco", "Error en operación", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_crearMouseClicked

    private void visualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarMouseClicked
        FListas fl = new FListas();
        fl.setVisible(true);
        fl.setInterfazbarco(this);
        fl.insertarModeloTabla("barco");
        setVisible(false);
    }//GEN-LAST:event_visualizarMouseClicked

    private void actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseClicked
        visibilidad(true);
        cargarListaBarcos();
        limpiarCajas();
        textoEliminar.setText("Regresar");
    }//GEN-LAST:event_actualizarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        if (textoEliminar.getText().equals("Regresar")) {
            visibilidad(false);
            textoEliminar.setText("Eliminar");
            textoActualizar.setText("Actualizar");
        } else {
            textoActualizar.setText("Eliminar");
            textoEliminar.setText("Regresar");
            visibilidad(true);
            cargarListaBarcos();
            textoEliminar.setVisible(true);
            cajaNombre.setEnabled(false);
            comboAmarre.setEnabled(false);
            botonGuardar.setText("Borrar");
        }
    }//GEN-LAST:event_eliminarMouseClicked

    private void limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMouseClicked
        limpiarCajas();
    }//GEN-LAST:event_limpiarMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        if (barcoBD != null) {
            barcoBD.cerrarConexion();
        }
        setVisible(false);
        new FMenu().setVisible(true);
    }//GEN-LAST:event_MenuMouseClicked

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if (comboMatricula.getSelectedIndex() != -1) {
            b = barcoBD.cargarDatos(comboMatricula.getItemAt(comboMatricula.getSelectedIndex()));
            comboMatricula.setEnabled(false);
            comboAmarre.setSelectedItem(b.getNumeroAmarre());
            comboPropietario.setSelectedItem(b.getIdentificacionDueño());
            cajaNombre.setText(b.getNombre());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (comboMatricula.getSelectedIndex() != -1) {
            if (botonGuardar.getText().equals("Borrar")) {
                barcoBD.eliminar(comboMatricula.getSelectedItem().toString());
            } else {
                if (comboPropietario.getSelectedIndex() != -1 && comboAmarre.getSelectedIndex() != -1 && !cajaNombre.getText().isEmpty()) {
                    b.setNumeroMatricula(Integer.parseInt(comboMatricula.getSelectedItem().toString()));
                    b.setNumeroAmarre(comboAmarre.getSelectedItem().toString());
                    b.setIdentificacionDueño(comboPropietario.getSelectedItem().toString());
                    b.setNombre(cajaNombre.getText());
                    barcoBD.actualizarBarco(b);
                    limpiarCajas();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falto uno de los datos número de matricula, número de amarre, propietario o nombre del barco", "Error en operación", JOptionPane.ERROR_MESSAGE);
        }
        textoEliminar.setText("Eliminar");
        activar(true);
        visibilidad(false);
        limpiarCajas();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void cajaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreKeyTyped
        limitarLetrasCajas(20, cajaNombre, evt);
    }//GEN-LAST:event_cajaNombreKeyTyped

    private void cajaMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaMatriculaKeyTyped
        limitarLetrasCajas(11, cajaMatricula, evt);
    }//GEN-LAST:event_cajaMatriculaKeyTyped
    
    //Metodos propios
      
    private void limpiarCajas () {
        cajaMatricula.setText("");
        cajaNombre.setText("");
        comboPropietario.setSelectedIndex(-1);
        comboAmarre.setSelectedIndex(-1);
    }
    
    private void cargarInterfazABarco () {
        String matricula = cajaMatricula.getText();
        String amarre = comboAmarre.getSelectedItem().toString();
        String propietario = comboPropietario.getSelectedItem().toString();
        String Nombre = cajaNombre.getText();
        b = new Barco(Integer.parseInt(matricula), amarre, propietario, Nombre, false);
    }
    
    private void activar (boolean estado) {
        cajaNombre.setEnabled(estado);
        textoActualizar.setVisible(estado);
    }
    
    private void visibilidad (boolean estado) {
        comboMatricula.setVisible(estado);
        textoIdentificacionEditar.setVisible(estado);
        botonBuscar.setVisible(estado);
        botonGuardar.setVisible(estado);
        comboMatricula.setEnabled(estado);
        estado = !estado;
        textoIdentificacionCrear.setVisible(estado);
        cajaMatricula.setVisible(estado);
        crear.setEnabled(estado);
        visualizar.setEnabled(estado);
        eliminar.setEnabled(estado);
        textoCrear.setVisible(estado);
        textoVisualizar.setVisible(estado);
        jLabel1.setVisible(estado);
        jLabel3.setVisible(estado);
        jLabel10.setVisible(estado);
    }
    
    //Limita la cantidad de texto que se le ingresa a la cajas de texto
    private void limitarLetrasCajas (int limite, javax.swing.JTextField caja, java.awt.event.KeyEvent e) {
        if (caja.getText().length() >= limite) {
            getToolkit().beep();
            e.consume();
        }
    }
    
    private void cargarListaBarcos () {
        LinkedList lista = barcoBD.listaBarcos();
        comboMatricula.removeAllItems();
        for (int i = 0; i < lista.size(); i++) {
            comboMatricula.addItem(lista.get(i).toString());
        }
        comboMatricula.setSelectedIndex(-1);
    }
    
    private void cargarListas () {
        PSocio idSocio = new PSocio();
        LinkedList lista = idSocio.identificaciones();
        comboPropietario.removeAllItems();
        comboAmarre.removeAllItems();
        for (int i = 0; i < lista.size(); i++) {
            comboPropietario.addItem(lista.get(i).toString());
        }
        comboPropietario.setSelectedIndex(-1);
        
        //Llenar lista de amarres solo los que este disponibles
        lista = barcoBD.listaAmarres();
        String numeroAmarre;
        for (int i = 0; i < 30; i++) {
            numeroAmarre = "A-" + i;
            for (int j = 0; j < lista.size(); j++) {
                if (!numeroAmarre.equals(lista.get(j))) { //Verifica disponibilidad
                    comboAmarre.addItem(numeroAmarre);
                }
            }
        }
        comboAmarre.setSelectedIndex(-1);
        idSocio.cerrarConexion();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBarco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Lateral;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel actualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField cajaMatricula;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel cerrar;
    private javax.swing.JComboBox<String> comboAmarre;
    private javax.swing.JComboBox<String> comboMatricula;
    private javax.swing.JComboBox<String> comboPropietario;
    private javax.swing.JPanel crear;
    private javax.swing.JPanel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel limpiar;
    private javax.swing.JLabel textoActualizar;
    private javax.swing.JLabel textoCrear;
    private javax.swing.JLabel textoEliminar;
    private javax.swing.JLabel textoIdentificacionCrear;
    private javax.swing.JLabel textoIdentificacionEditar;
    private javax.swing.JLabel textoPropietario;
    private javax.swing.JLabel textoVisualizar;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel visualizar;
    // End of variables declaration//GEN-END:variables
}
